pep_version: "2.0.0"
sample_table: sample_table.csv
output_dir: $HOME/hello_looper_results

sample_modifiers:
  derive:
    attributes: [file_path]
    sources:
      source1: /data/lab/project/{organism}_{genome}_{condition}.fastq
  imply:
    - if:
        organism: pig
      then:
        genome: susScr11
    - if:
        organism: frog
      then:
        genome: xenTro9
    - if:
        time: "0"
      then:
        condition: untreated
    - if:
        time: "1"
      then:
        condition: treated
