FROM tiangolo/uvicorn-gunicorn:python3.8
LABEL authors="Nathan LeRoy, Michal Stolarczyk, Nathan Sheffield"

COPY . /app
RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /app/requirements/requirements-all.txt