version: '3.8'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./pephub/:/app/pephub/
    command: uvicorn pephub.main:app --reload --workers 4 --host 0.0.0.0 --port 8000
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=pep-base-sql
    ports:
      - 5432:5432
volumes:
    postgres_data: