FROM tiangolo/uvicorn-gunicorn:python3.8

COPY . /app

# download the pep for testing
WORKDIR /app
RUN pip install --upgrade pip
RUN pip install -r requirements/requirements-all.txt
RUN python /app/pephub/db.py

CMD ["pytest", "./tests"]