version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    networks:
      - pephub
    env_file:
      - .env
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./pephub/:/app/pephub/
    command: uvicorn pephub.main:app --reload --workers 4 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - pephub
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db

volumes:
  postgres-data:

networks:
  pephub:
    driver: bridge
