pep_version: "2.0.0"
sample_table: sample_table.csv
subsample_table: subsample_table.csv
looper:
  output_dir: $HOME/hello_looper_results
  pipeline_interfaces: [../pipeline/pipeline_interface.yaml]

sample_modifiers:
  derive:
    attributes: [read1, read2]
    sources:
      R1: "../data/{identifier}{file_id}_R1.fq.gz"
      R2: "../data/{identifier}{file_id}_R2.fq.gz"
