pep_version: "2.0.0"
sample_table: "pep_samples.csv"
subsample_table: "pep_subsamples_derived.csv"

sample_modifiers:
  derive:
    attributes: 
      - read1
      - read2
    sources:
      read1: https://raw.githubusercontent.com/nf-core/test-datasets/rnaseq/testdata/GSE110004/{SRR}_1.fastq.gz
      read2: https://raw.githubusercontent.com/nf-core/test-datasets/rnaseq/testdata/GSE110004/{SRR}_2.fastq.gz
