pep_version: '2.0.0'
sample_table: sample_table.csv
looper:
  output_dir: $HOME/hello_looper_results

sample_modifiers:
  imply:
    - if:
        organism: human
      then:
        genome: hg38
        macs_genome_size: hs
    - if:
        organism: mouse
      then:
        genome: mm10
        macs_genome_size: mm
