pep_version: "2.0.0"
sample_table: sample_table.csv
output_dir: "$HOME/hello_looper_results"

sample_modifiers:
  derive:
    attributes: [file_path]
    sources:
      source1: $HOME/data/lab/project/{organism}_{time}h.fastq
      source2: /path/from/collaborator/weirdNamingScheme_{external_id}.fastq
