on:
  release:
    types:
      - created
  workflow_dispatch:
    inputs: null

name: Deploy to Dockerhub on release

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          push: true
          context: '{{defaultContext}}:deployment/dockerhub'
          tags: databio/pephub:latest
